<?php

namespace Jobi\WebinarNetworkingInterviewPodcast\Database\Seeders;

use Illuminate\Database\Seeder;
use Jobi\WebinarNetworkingInterviewPodcast\Models\Interview;
use Jobi\WebinarNetworkingInterviewPodcast\Models\NetworkingSession;
use Jobi\WebinarNetworkingInterviewPodcast\Models\PodcastSeries;
use Jobi\WebinarNetworkingInterviewPodcast\Models\Webinar;

class WebinarNetworkingInterviewPodcastSeeder extends Seeder
{
    public function run(): void
    {
        $hostId = config('webinar_networking_interview_podcast.seeder_host_id', 1);

        foreach (range(1, 3) as $index) {
            Webinar::create([
                'host_id' => $hostId,
                'title' => "Sample Webinar {$index}",
                'description' => 'Generated seed webinar for onboarding flows.',
                'status' => 'scheduled',
                'starts_at' => now()->addDays($index),
                'ends_at' => now()->addDays($index)->addHours(1),
                'is_paid' => false,
                'price' => 0,
            ]);
        }

        foreach (range(1, 2) as $index) {
            NetworkingSession::create([
                'host_id' => $hostId,
                'title' => "Speed Networking {$index}",
                'description' => 'Autogenerated networking session.',
                'duration_seconds' => 1800,
                'rotation_interval' => 180,
                'starts_at' => now()->addDays($index + 1),
                'is_paid' => false,
            ]);
        }

        foreach (range(1, 2) as $index) {
            PodcastSeries::create([
                'host_id' => $hostId,
                'title' => "Podcast Series {$index}",
                'description' => 'Seeded professional insights series.',
                'is_public' => true,
            ]);
        }

        foreach (range(1, 2) as $index) {
            Interview::create([
                'host_id' => $hostId,
                'title' => "Interview Round {$index}",
                'description' => 'Seeded interview schedule.',
                'scheduled_at' => now()->addDays(5 + $index),
                'duration_minutes' => 60,
                'is_panel' => true,
            ]);
        }
    }
}

